services:
  - docker
  - redis-server

env:
  global:
    - DOCKER_REPO="oanhnn/laravel-echo-server"
    #- DOCKER_USER
    #- DOCKER_PASSWORD
  matrix:
    - LES_DB="sqlite"
    - LES_DB="redis"

before_script:
  - docker info
  - export BUILD_TAG=${TRAVIS_COMMIT::8}

script:
  - echo "=> Building the image"
  - docker pull $DOCKER_REPO:latest || true
  - docker build --cache-from $DOCKER_REPO:latest
                 --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
                 --build-arg VCS_REF=`git rev-parse --short HEAD`
                 --build-arg VERSION=${TRAVIS_TAG:-'latest'}
                 --tag $DOCKER_REPO:$BUILD_TAG --pull --compress .

  - docker run -d --net="host" --env LES_DB=$LES_DB $DOCKER_REPO:$BUILD_TAG
  - sleep 60 && docker ps
  - curl --retry 10 --retry-delay 2 -I http://127.0.0.1:6001/socket.io/socket.io.js

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker tag $DOCKER_REPO:$BUILD_TAG $DOCKER_REPO:latest;
      docker push $DOCKER_REPO:latest;
    fi
  - if [[ ! -z "$TRAVIS_TAG" ]]; then
      docker tag $DOCKER_REPO:$BUILD_TAG $DOCKER_REPO:$TRAVIS_TAG;
      docker push $DOCKER_REPO:$TRAVIS_TAG;
    fi
