services:
  - docker
  - redis-server

env:
  global:
    - DOCKER_REPO="oanhnn/laravel-echo-server"
    #- DOCKER_USER
    #- DOCKER_PASSWORD
  matrix:
    - LARAVEL_ECHO_SERVER_DB="sqlite"
    - LARAVEL_ECHO_SERVER_DB="redis"

before_script:
  - docker info
  - export BUILD_TAG=${TRAVIS_COMMIT::8}
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export BUILD_VERSION=${TRAVIS_TAG:-'latest'}
  - export VCS_REF=`git rev-parse --short HEAD`

script:
  - echo "=> Building the image"
  - docker pull $DOCKER_REPO:latest || true
  - docker build --label "org.label-schema.build-date=$BUILD_DATE"
                 --label "org.label-schema.name='Laravel Echo Server Docker Image'"
                 --label "org.label-schema.description='The Docker Image for run Laravel Echo Server'"
                 --label "org.label-schema.url='https://github.com/oanhnn/docker-laravel-echo-server'"
                 --label "org.label-schema.vcs-url='https://github.com/oanhnn/docker-laravel-echo-server.git'"
                 --label "org.label-schema.vcs-ref=$VCS_REF"
                 --label "org.label-schema.version=$BUILD_VERSION"
                 --label "org.label-schema.schema-version=1.0"
                 --cache-from $DOCKER_REPO:latest
                 --tag $DOCKER_REPO:$BUILD_TAG --pull --compress .

  - docker run -d --net="host" -e REDIS_HOST=localhost -e LARAVEL_ECHO_SERVER_DB=$LARAVEL_ECHO_SERVER_DB $DOCKER_REPO:$BUILD_TAG
  - sleep 60 && docker ps
  - curl --retry 10 --retry-delay 2 -I http://127.0.0.1:6001/socket.io/socket.io.js

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      docker tag $DOCKER_REPO:$BUILD_TAG $DOCKER_REPO:latest;
      docker push $DOCKER_REPO:latest;
    fi
  - if [[ ! -z "$TRAVIS_TAG" ]]; then
      docker tag $DOCKER_REPO:$BUILD_TAG $DOCKER_REPO:$TRAVIS_TAG;
      docker push $DOCKER_REPO:$TRAVIS_TAG;
    fi
