version: "3"

volumes:
  sqlite-vol: {}

services:
  laravel-echo-server:
    image: oanhnn/laravel-echo-server:3.1
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: http://example.com
      LARAVEL_ECHO_SERVER_DEBUG:     'true'
      LARAVEL_ECHO_SERVER_DATABASE:  sqlite
    ports:
      - 6001:6001
    restart: unless-stopped
    volumes:
      - sqlite-vol:/database
